### ISSUE TITLE
Mislabelling of data

### ISSUE THREAD

**Issue by harsmac** [ykotseruba/JAAD_behavior#1]
Could someone explain how this is cloudy and not snow? There seem to be many such misnomers. At least two tags should have been added instead. This also seems to be the case with many images, a typical snowy case called clear or rain etc. **Please verify.** 
![video_0343 frame 0020](https://user-images.githubusercontent.com/15107872/48423086-f44aa780-e785-11e8-9cdd-b0bc3ab12669.png)

This is video 343 and as per the search on the website it's cloudy

**Comment by ykotseruba** [comment]
The data is not mislabeled. There are separate tags for road conditions and weather conditions. Basically if the snow or rain is actually falling from the sky, we label the weather conditions as such, otherwise it is clear or cloudy. If the road surface is covered with snow we label it as snow, otherwise it is wet or dry. There are no labels for the condition of the sidewalks. 
The logic behind our weather labels is not based on whether you can see snow somewhere in the image, but whether the visibility is affected. If the weather is clear, there will be sharp shadows, if it is snowing/raining the driver won't see as far. For the roads we care about the handling of the car: if the road is wet or covered with snow, this will affect the behavior of the driver and possibly behaviors of  pedestrians crossing the street. This labeling is consistent throughout the dataset.
In the particular video you are referring to it is not snowing and the visibility is not affected, so it is labeled as cloudy. The road in this video is not covered with snow, but is wet so it is labeled accordingly.

**Comment by harsmac** [comment]
I understand the approach that you mentioned but I am not very sure it's consistent. 
For example, video_0117 has rain droplets occurring in the visibility of the screen and yet its labeled as clear.
<img width="1387" alt="screen shot 2018-11-14 at 12 20 48 am" src="https://user-images.githubusercontent.com/15107872/48435732-2ddddb80-e7a3-11e8-89a0-a105a0dc10ce.png">

**Comment by ykotseruba** [comment]
In video 0117 its early morning and the driver is using wipers to clean the morning dew from the windshield for a few frames in the beginning. It can be seen that the weather is clear (it is not raining) in this video.
