### ISSUE TITLE
How are you using BORIS for pedestrian behavior 

### ISSUE THREAD

**Issue by aalzooke** [ykotseruba/JAAD_behavior#2]
Just want to know how are you using BORIS for pedestrian behavior? does the bounding boxes data must be the same for BORIS labeling? 
What tool do you recommend if BORIS may not be the best tool for pedestrian behavior? Amir mentioned that CVAT better
Please share your ideas and advice. 
Thank you

**Comment by ykotseruba** [comment]
BORIS is a tool that lets the user to define a set of behavior tags and go through the video to set timestamps  for beginning/end of each defined behavior. BORIS doesn't use bounding box data, so it becomes tricky to assign behaviors to multiple subjects within a single video because there is no way of highlighting a subject of interest which can lead to errors. Most of our clips contained few pedestrians that needed to be annotated, but in crowded scenes BORIS would probably be difficult to use. Finally, BORIS annotations must be synchronized with the bounding box data. It's not difficult, but it's an extra processing step, so yet another possibility of introducing errors/noise to the data. 

CVAT avoids these complications since it allows to assign arbitrary text tags for bounding boxes and exports them all in a single xml file.  As Amir mentioned to you, we switched to CVAT only recently since it was not available at the time when we started working on JAAD. For the sort of annotations we did in JAAD (bounding boxes, pedestrian attributes and behavior annotations) CVAT is probably the best free tool available. There might be better commercial tools, but we did not look into that.
I hope this answers your question.

**Comment by aalzooke** [comment]
Thank you so much for making this very clear, yes I was wondering about using BORIS since there are many pedestrians in our dataset especially in an urban environment. regarding CVAT, are you adding the metadata for every pedestrian you are labeling? I have not used CVAT so I'm just wondering how you are classifying crossing, not crossing, etc..

**Comment by ykotseruba** [comment]
We did not use CVAT for labelling pedestrians in JAAD dataset, so I cannot answer your questions regarding the metadata or crossing/not crossing labels. Perhaps you can check the documentation or refer this question to someone from the CVAT community.
